### ISSUE TITLE
Failing to install in Laravel 9 projects due to dependency conflicts

### ISSUE THREAD

**Issue by wesort** [steadfast-collective/statamic-csv-exporter#1]
I've tried to install but I'm getting a `404` on `/cp/utilities/csv-exporter` 

![csv-exporter-404](https://user-images.githubusercontent.com/3920126/171207184-7039b1e5-0b86-4184-aff7-eef457c11dc5.png)

## Install attempts:
1. via the CP (Tools > Addons) 
2. Manually with: `composer require steadfastcollective/statamic-csv-exporter`
<details><summary>Attempt 2: <b>Installation failed...</b></summary>
<pre>
Problem 1
    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phpoffice/phpspreadsheet 1.23.0 requires psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.0.16) does not satisfy that requirement.
    - maatwebsite/excel[3.1.26, ..., 3.1.35] require illuminate/support 5.8.*|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - steadfastcollective/statamic-csv-exporter[v1.0.0, ..., v1.0.1] require maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].
    - maatwebsite/excel[3.1.36, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.23.0].
    - Root composer.json requires steadfastcollective/statamic-csv-exporter ^1.0 -> satisfiable by steadfastcollective/statamic-csv-exporter[v1.0.0, v1.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require steadfastcollective/statamic-csv-exporter:*" to figure out if any version is installable, or "composer require steadfastcollective/statamic-csv-exporter:^2.1" if you know which you need.
</pre>
</details>

3. Manually with: `composer require steadfastcollective/statamic-csv-exporter -W`

Am I missing an obvious step?

## Details
Statamic 3.3.12 Pro
Laravel 9.14.1
PHP 8.0.16
aryehraber/statamic-uuid 2.1.0
rias/statamic-data-import 1.2.1

**Comment by duncanmcclean** [comment]
So, so sorry! Just realised I wasn't watching this repository so didn't get notified by your issue.

It seems like the CSV Exporter addon isn't being installed due to conflicts with other dependencies in your project. 

I've just tried installing this addon to a fresh Statamic site and I'm seeing the same issue. Will try and carve some time out this week to fix it 🙏

**Comment by duncanmcclean** [comment]
Hmm, it seems like `phpoffice/phpspreadsheet` package (which we use via Laravel Excel) isn't compatible with `psr/simple-cache` v3 which is a package I believe included by Laravel.

In my testing last night, I was able to install fine when providing the `-W` flag to composer. I'm aware it's a bit of a workaround but I'll update the install instructions to include that parameter so it's still actually installable.

If you're still having issues after providing that parameter, please open another issue 😃
